runtime: php73

handlers:
- url: /vendor/material-dashboard
  static_dir: public/vendor/material-dashboard



# - url: /(.*\.(gif|png|jpg|css|js))$
#   static_files: public/\1
#   upload: public/.*\.(gif|png|jpg|css|js)$

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:V4WqGxKE5frynoinoaY5/LUfPEsajzTxbuXGAegdohQ=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie

  DB_HOST: 34.92.63.140
  DB_DATABASE: accountapp
  DB_USERNAME: root
  DB_PASSWORD: wallecommerce
  DB_SOCKET: "/cloudsql/poised-epigram-307002:asia-east2:account-app"
  APP_DEBUG: true
  APP_LOG: errorlog
  # APP_DEBUG: false

beta_settings:
  cloud_sql_instances: "poised-epigram-307002:asia-east2:account-app"
