runtime: php73

handlers:
- url: /vendor/material-dashboard
  static_dir: public/vendor/material-dashboard



# - url: /(.*\.(gif|png|jpg|css|js))$
#   static_files: public/\1
#   upload: public/.*\.(gif|png|jpg|css|js)$

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:V4WqGxKE5frynoinoaY5/LUfPEsajzTxbuXGAegdohQ=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  # APP_DEBUG: false
